// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStoreApplication.Repository;

#nullable disable

namespace MusicStore.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250205192823_BoughtItemFix")]
    partial class BoughtItemFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlbumImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eccc5564-1c78-4f64-8df6-7bef07339902"),
                            AlbumImageUrl = "https://i.discogs.com/1fwskTLM6cfxbdNmBDJ8expl6wab0tEgxvuloLIqKh8/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTkyODc4/MDktMTQ3OTc1MzIz/Ni05NjE3LmpwZWc.jpeg",
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Price = 20,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Side of the Moon"
                        },
                        new
                        {
                            Id = new Guid("a6968856-eb50-49ed-9e5a-878bcc47361d"),
                            AlbumImageUrl = "https://i.discogs.com/pZnTKUeiKsxSyvX_87YMgccx0bq5sjqThFH9iSNAtAY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYw/OTctOTI4MC5qcGVn.jpeg",
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Price = 22,
                            ReleaseDate = new DateTime(1975, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wish You Were Here"
                        },
                        new
                        {
                            Id = new Guid("d1376baa-a7b0-4967-9064-1a6b375e8e80"),
                            AlbumImageUrl = "https://i.discogs.com/goWfjpqUBW8Y0xrqJG_GFz3fCTHPSWeKLZAX1alAAzk/rs:fit/g:sm/q:90/h:600/w:592/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MTg2/NDQxLTE1Njk0ODcx/NjEtNzMxNC5qcGVn.jpeg",
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Price = 25,
                            ReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Abbey Road"
                        },
                        new
                        {
                            Id = new Guid("528c1b7a-008b-4e91-9c5d-81f0a6709a53"),
                            AlbumImageUrl = "https://i.discogs.com/HWA3uoT2xu7zj_kM-f18f02CCQNKk2W8YzUL-D_l2ZM/rs:fit/g:sm/q:90/h:581/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwODgx/MjYtMTI1Njk1MDk3/OS5qcGVn.jpeg",
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Price = 23,
                            ReleaseDate = new DateTime(1970, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Let It Be"
                        },
                        new
                        {
                            Id = new Guid("fbdf9ad3-5d89-4f09-b19b-a1fc90977ac6"),
                            AlbumImageUrl = "https://i.discogs.com/yFq3X0xZMxIVHIFgmbrsPvJHXLJCfVLWs60AL4XS4bs/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTM2NjMxMTg2/Ny0yNzg1LmpwZWc.jpeg",
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Price = 24,
                            ReleaseDate = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Led Zeppelin IV"
                        },
                        new
                        {
                            Id = new Guid("ec9d3f10-5139-4c12-944b-25da7c55742a"),
                            AlbumImageUrl = "https://i.discogs.com/BLWVi0t0llSqJvIybHrSvPql-RfORCmZU1klNfV0si8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xNTg4ODgwNzg4/LTIyMjYuanBlZw.jpeg",
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Price = 26,
                            ReleaseDate = new DateTime(1973, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Houses of the Holy"
                        },
                        new
                        {
                            Id = new Guid("e544c543-0017-44cf-aa2e-b300208c4d4e"),
                            AlbumImageUrl = "https://i.discogs.com/2GXnNYolz0ciUnj8-ycSwQ8Uuy0Qu7LCfiZivZ0p_bo/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQ1/LTIxMjcuanBlZw.jpeg",
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Price = 21,
                            ReleaseDate = new DateTime(1975, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Night at the Opera"
                        },
                        new
                        {
                            Id = new Guid("cffaea35-dd5a-4a27-aab1-b57c2be9743f"),
                            AlbumImageUrl = "https://i.discogs.com/p2o5GGONaTq4jK398iU0X3KjuMfnK10_TEC_bdnKA6k/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzMjg5/ODItMTM1NzgxOTE3/NS05NTU3LmpwZWc.jpeg",
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Price = 19,
                            ReleaseDate = new DateTime(1984, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Works"
                        },
                        new
                        {
                            Id = new Guid("a35a51d6-87a1-4989-a806-08494acf98e8"),
                            AlbumImageUrl = "https://i.discogs.com/XoAXkLe03Vk0Kt-oQqw7V9uW5nBzQdNvZd0zar5mOiQ/rs:fit/g:sm/q:90/h:592/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2NzA4/NC0xMjYzMDk1NTUz/LmpwZWc.jpeg",
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Price = 18,
                            ReleaseDate = new DateTime(1991, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nevermind"
                        },
                        new
                        {
                            Id = new Guid("12c850aa-c450-4af7-bb7b-7e98d5ce4956"),
                            AlbumImageUrl = "https://i.discogs.com/ijIUNhH--0OKzKuKv-aLpgFkb7lr6OQVb5FcAF_aW0U/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NTk3/OS0xNDkxNzAwMzQ3/LTcyNjMuanBlZw.jpeg",
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Price = 20,
                            ReleaseDate = new DateTime(1993, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "In Utero"
                        });
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Bio = "A legendary rock band.",
                            Name = "Pink Floyd"
                        },
                        new
                        {
                            Id = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Bio = "One of the most influential rock bands.",
                            Name = "The Beatles"
                        },
                        new
                        {
                            Id = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Bio = "A rock band known for its heavy sound.",
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            Id = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Bio = "A rock band known for its eclectic musical style.",
                            Name = "Queen"
                        },
                        new
                        {
                            Id = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Bio = "A grunge band that shaped the 90s music scene.",
                            Name = "Nirvana"
                        });
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.BoughtItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("BoughtItems");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MusicStoreApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MusicStoreApplicationUserId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrackImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d65256df-b0d3-4824-9ede-f49b0007cf4c"),
                            AlbumId = new Guid("eccc5564-1c78-4f64-8df6-7bef07339902"),
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Duration = new TimeSpan(0, 0, 1, 0, 0),
                            Price = 129,
                            Title = "Speak to Me",
                            TrackImageUrl = "https://i.discogs.com/E9E7stvIt5YKUfK_CnrpIgxchviC7Q4WCeyQuuICAjo/rs:fit/g:sm/q:90/h:397/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTI0OTMwMDYw/MC5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("4a0278bf-7d05-4141-b618-2bf4da8ae7a6"),
                            AlbumId = new Guid("eccc5564-1c78-4f64-8df6-7bef07339902"),
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Duration = new TimeSpan(0, 0, 2, 0, 0),
                            Price = 129,
                            Title = "Breathe in the air",
                            TrackImageUrl = "https://i.discogs.com/mfba8kz9-PIwZGE5g70Z5i6JpITmeRfaXLsWClcxj8g/rs:fit/g:sm/q:90/h:500/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4NzAw/MjYwLTE2OTgyMzg5/MDItNDY5NS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("58ffcd2a-17ae-4589-9ca6-7eeb1528b5bd"),
                            AlbumId = new Guid("eccc5564-1c78-4f64-8df6-7bef07339902"),
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "On the Run",
                            TrackImageUrl = "https://i.discogs.com/t4BbENT4ugUFTY-pgCqTcEHhlfwlrJeJuyTOTzqxKfM/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTcyNzc2NDky/OS03ODUzLmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("23bec2de-d42b-4b2e-a5a3-e3bf961cba5d"),
                            AlbumId = new Guid("eccc5564-1c78-4f64-8df6-7bef07339902"),
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Duration = new TimeSpan(0, 0, 6, 0, 0),
                            Price = 129,
                            Title = "Time",
                            TrackImageUrl = "https://i.discogs.com/rCpj_7gUWtxKDPQQpoVwbrud6zN2wwyQRVFR-ZaNtFI/rs:fit/g:sm/q:90/h:380/w:577/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTI0OTMwMDU4/MS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("dc2f9861-4e0c-46aa-9e3d-b9460de64d6c"),
                            AlbumId = new Guid("a6968856-eb50-49ed-9e5a-878bcc47361d"),
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Duration = new TimeSpan(0, 0, 13, 0, 0),
                            Price = 129,
                            Title = "Shine On You Crazy Diamond (Part I-V)",
                            TrackImageUrl = "https://i.discogs.com/pZnTKUeiKsxSyvX_87YMgccx0bq5sjqThFH9iSNAtAY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYw/OTctOTI4MC5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("96229957-8617-4863-89ec-6da73cf4d164"),
                            AlbumId = new Guid("a6968856-eb50-49ed-9e5a-878bcc47361d"),
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Duration = new TimeSpan(0, 0, 7, 0, 0),
                            Price = 129,
                            Title = "Welcome to the Machine",
                            TrackImageUrl = "https://i.discogs.com/a36kcqXYhsvwN7S1cyq8_CGqqyWi78u3CLtxuE86-Go/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYw/OTYtMTc3Mi5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("6aeb51b0-f1b4-4823-90ba-28416a8ce1ea"),
                            AlbumId = new Guid("a6968856-eb50-49ed-9e5a-878bcc47361d"),
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Have a Cigar",
                            TrackImageUrl = "https://i.discogs.com/frk8i23GN3Epw5RaA-um7KwmBw0NTQiEHUYtirXaqdg/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYx/MDgtMTIxMi5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("7647b0fe-7089-4521-a350-6355f88e7aea"),
                            AlbumId = new Guid("a6968856-eb50-49ed-9e5a-878bcc47361d"),
                            ArtistId = new Guid("e0194146-5167-432c-a2ac-389322a5f9e4"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Wish You Were Here",
                            TrackImageUrl = "https://i.discogs.com/hJBh2v_V6Ow6_hyPu791g1d_Pqj6_aoKB6fm_JUKUPA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYx/MjgtNDE1My5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("34fd5e9c-6adb-4f13-aca9-d4127fa3b5f7"),
                            AlbumId = new Guid("d1376baa-a7b0-4967-9064-1a6b375e8e80"),
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Come Together",
                            TrackImageUrl = "https://i.discogs.com/M2yc5OJZPdVoDm2_UlRRXuDlDguamLLSdnbziNmZoQI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MDc0/MjQtMTYzMDYwMTA4/Ny0xMTk5LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("585ae788-c59f-44da-9562-a8d075efba54"),
                            AlbumId = new Guid("d1376baa-a7b0-4967-9064-1a6b375e8e80"),
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Something",
                            TrackImageUrl = "https://i.discogs.com/M2yc5OJZPdVoDm2_UlRRXuDlDguamLLSdnbziNmZoQI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MDc0/MjQtMTYzMDYwMTA4/Ny0xMTk5LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("59b7e1f3-7c71-4b8a-b80c-5eef2bdb19fd"),
                            AlbumId = new Guid("d1376baa-a7b0-4967-9064-1a6b375e8e80"),
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Octopus's Garden",
                            TrackImageUrl = "https://i.discogs.com/M2yc5OJZPdVoDm2_UlRRXuDlDguamLLSdnbziNmZoQI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MDc0/MjQtMTYzMDYwMTA4/Ny0xMTk5LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("ff310da1-2f05-4df6-9a52-431e1555ccb9"),
                            AlbumId = new Guid("d1376baa-a7b0-4967-9064-1a6b375e8e80"),
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Here Comes the Sun",
                            TrackImageUrl = "https://i.discogs.com/qsJyhu9LR8BERwbo5DRIYdNJzZFyuxQMr3RJcnOSEkw/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgxMzcz/NTUtMTQ1NTgzODU3/My0zNDk0LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("fff5dd38-f443-4729-b9ec-7db917ba56d3"),
                            AlbumId = new Guid("528c1b7a-008b-4e91-9c5d-81f0a6709a53"),
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Let It Be",
                            TrackImageUrl = "https://i.discogs.com/hAdrrjfnT2klIYc1V_oKX5HjpJ3xElwd7FDaDydTFGo/rs:fit/g:sm/q:90/h:600/w:566/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzU1/NC0xMzQ0NTE5Njg4/LTU0MzkuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("fd62f17a-c23c-4a09-b40f-57a7f7c45cf6"),
                            AlbumId = new Guid("528c1b7a-008b-4e91-9c5d-81f0a6709a53"),
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Across the Universe",
                            TrackImageUrl = "https://i.discogs.com/KFfU_VOBY43WsttSMHMp0uUvaQ8Sk63qAoCDeTeENpE/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzU1/NC0xMzQ1NjcxNjIy/LTM1ODYuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("87146a48-95fd-4b3d-aa77-d0817eb09854"),
                            AlbumId = new Guid("528c1b7a-008b-4e91-9c5d-81f0a6709a53"),
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "The Long and Winding Road",
                            TrackImageUrl = "https://i.discogs.com/3C94Ivdig0n1Jyb8d_0jKoIvj54r56hYW6kb6kiM8cY/rs:fit/g:sm/q:90/h:600/w:595/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzU1/NC0xMzI2NzA0NzMw/LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("af40ac5c-aca5-4470-8756-3f1372c97cb5"),
                            AlbumId = new Guid("528c1b7a-008b-4e91-9c5d-81f0a6709a53"),
                            ArtistId = new Guid("e42f6997-b85e-4fb8-801e-7d8c526f07a3"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Get Back",
                            TrackImageUrl = "https://i.discogs.com/yZ8hA52tgMGcdxfY182_OqxJIjUuzu1NvwVKxNM_Ztg/rs:fit/g:sm/q:90/h:599/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzU1/NC0xMzI2NzA0NzIw/LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("f99742bc-0ed1-4c71-a3bb-20598e7f38fa"),
                            AlbumId = new Guid("fbdf9ad3-5d89-4f09-b19b-a1fc90977ac6"),
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Black Dog",
                            TrackImageUrl = "https://i.discogs.com/Ok43Qrm9pIMNTCCCR5oXwL9XU_0_WxXdRl6RKeXfxBg/rs:fit/g:sm/q:90/h:600/w:595/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTU5Mjc0NzQ3/My00NDI0LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("52f0255f-070a-45a5-b26c-f53cdce6a519"),
                            AlbumId = new Guid("fbdf9ad3-5d89-4f09-b19b-a1fc90977ac6"),
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Rock and Roll",
                            TrackImageUrl = "https://i.discogs.com/aFc_fainrAcSiX2MbERPPWWlvjeYKc0D4yf53WD4rzM/rs:fit/g:sm/q:90/h:592/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTU5Mjc0NzQ3/NC00ODYwLmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("adfdeb6b-c954-4f2d-ac00-adc010c3c168"),
                            AlbumId = new Guid("fbdf9ad3-5d89-4f09-b19b-a1fc90977ac6"),
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Duration = new TimeSpan(0, 0, 8, 0, 0),
                            Price = 129,
                            Title = "Stairway to Heaven",
                            TrackImageUrl = "https://i.discogs.com/AO-PmjrMZa3JNJ8NBErUUcDOJ2Yna2jCNLbwmZ0n9aE/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc1Nzg1/NC0xNTE1ODU0Mjcx/LTM3NDUuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("0e191fdb-60b1-4ed3-be63-3d3a2cf873ae"),
                            AlbumId = new Guid("fbdf9ad3-5d89-4f09-b19b-a1fc90977ac6"),
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Going to California",
                            TrackImageUrl = "https://i.discogs.com/kOYbkKoJqpZfHNMg38TaBrOQmJWYO8UoRWV_BOgR6MA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTM2NjMxMTg4/My02MDE1LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("be238550-1b70-4d33-8610-bf92bbb10139"),
                            AlbumId = new Guid("ec9d3f10-5139-4c12-944b-25da7c55742a"),
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "The Song Remains the Same",
                            TrackImageUrl = "https://i.discogs.com/PGoolvGRHExppmuvEDxPETmRJAFIlpoSAZ41ws86GLw/rs:fit/g:sm/q:90/h:577/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xMzkxNTIyMzA2/LTU4MzMuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("bd801c05-7f35-4992-b439-634d6b3f0cca"),
                            AlbumId = new Guid("ec9d3f10-5139-4c12-944b-25da7c55742a"),
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Duration = new TimeSpan(0, 0, 7, 0, 0),
                            Price = 129,
                            Title = "The Rain Song",
                            TrackImageUrl = "https://i.discogs.com/8wnDvfzEjV9Wc1BBxbaIIUeBhIxQ7WeFsKjdwt9hoWc/rs:fit/g:sm/q:90/h:574/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xMzkxNTIyMjY2/LTY4MzkuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("bdc9c004-8088-40a7-b151-c5c0cb83922c"),
                            AlbumId = new Guid("ec9d3f10-5139-4c12-944b-25da7c55742a"),
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Over the Hills and Far Away",
                            TrackImageUrl = "https://i.discogs.com/QVRkVVBO1gFfafoFfNzNps67VKs1DsGRcHQ474zEDf0/rs:fit/g:sm/q:90/h:224/w:452/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xMTcxOTI0MzQz/LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("4ea30dc8-40c2-4ad2-ab20-02f460250318"),
                            AlbumId = new Guid("ec9d3f10-5139-4c12-944b-25da7c55742a"),
                            ArtistId = new Guid("3bfda304-f53e-40f0-9b83-47235bbe506c"),
                            Duration = new TimeSpan(0, 0, 7, 0, 0),
                            Price = 129,
                            Title = "No Quarter",
                            TrackImageUrl = "https://i.discogs.com/BLWVi0t0llSqJvIybHrSvPql-RfORCmZU1klNfV0si8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xNTg4ODgwNzg4/LTIyMjYuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("59d1e554-07cb-4e9a-8f71-bbc0e3b75627"),
                            AlbumId = new Guid("e544c543-0017-44cf-aa2e-b300208c4d4e"),
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Death on Two Legs",
                            TrackImageUrl = "https://i.discogs.com/exLiE9TUHd1Osv4-SBjJsO8zScHQQ2s5XTA7QzvHmjk/rs:fit/g:sm/q:90/h:591/w:595/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQy/LTU2OTMuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("f0ea87c2-af87-47ec-9792-e2dcce62b532"),
                            AlbumId = new Guid("e544c543-0017-44cf-aa2e-b300208c4d4e"),
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "You're My Best Friend",
                            TrackImageUrl = "https://i.discogs.com/2GXnNYolz0ciUnj8-ycSwQ8Uuy0Qu7LCfiZivZ0p_bo/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQ1/LTIxMjcuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("9ff0170e-ea9c-4faa-b369-bd9583d25705"),
                            AlbumId = new Guid("e544c543-0017-44cf-aa2e-b300208c4d4e"),
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Love of My Life",
                            TrackImageUrl = "https://i.discogs.com/2GXnNYolz0ciUnj8-ycSwQ8Uuy0Qu7LCfiZivZ0p_bo/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQ1/LTIxMjcuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("227fad2d-aee0-48c8-b10e-827b3ee96bc4"),
                            AlbumId = new Guid("e544c543-0017-44cf-aa2e-b300208c4d4e"),
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Duration = new TimeSpan(0, 0, 6, 0, 0),
                            Price = 129,
                            Title = "Bohemian Rhapsody",
                            TrackImageUrl = "https://i.discogs.com/_RN78C49qgCxMX3CnRdxDggOCSI5P7uYaUGJ_Pl_CGM/rs:fit/g:sm/q:90/h:567/w:574/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2OTg5/MC0xMzkzMjg2NDQz/LTU3NTUuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("2e5ea6be-e58b-4182-b23f-c5aef0997a7b"),
                            AlbumId = new Guid("cffaea35-dd5a-4a27-aab1-b57c2be9743f"),
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Radio Ga Ga",
                            TrackImageUrl = "https://i.discogs.com/b20JvPlll2B74GR7tMh3oSukHbeTjq3cyTBpdKk25fA/rs:fit/g:sm/q:90/h:600/w:598/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1MTU5/MTEtMTU5OTIzODcx/MS05NjI1LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("884de3cf-5e51-457d-83e9-cfb95e37c2a8"),
                            AlbumId = new Guid("cffaea35-dd5a-4a27-aab1-b57c2be9743f"),
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Tear It Up",
                            TrackImageUrl = "https://i.discogs.com/TNq6BKsREuTvVL0QtgziQ0ACcLNhKq9AjP-NYI7yo14/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ3NTU5/Ni0xNDU0NzA3NDYw/LTIxNzkuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("78e65fe0-c016-4d02-a1cb-b5b36dd18bad"),
                            AlbumId = new Guid("cffaea35-dd5a-4a27-aab1-b57c2be9743f"),
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "It's a Hard Life",
                            TrackImageUrl = "https://i.discogs.com/gdK1Z8e8y1qZybHe6WF_NXUstJzEhHSId63nx0GS_Yo/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1OTU3/NTktMTIzMTA1Njkw/MS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("b70b210d-6235-4e98-9e9a-bab0625f162a"),
                            AlbumId = new Guid("cffaea35-dd5a-4a27-aab1-b57c2be9743f"),
                            ArtistId = new Guid("619a35b5-9004-46af-af82-a3bbd948c719"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "I Want to Break Free",
                            TrackImageUrl = "https://i.discogs.com/GZW57VCYRIgmdlkLRQwj_ZejpTs1lW3TiH-m5zJzvKg/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1NDU5/MDAtMTIyNzQzNTEx/NS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("d68102e8-a433-4b41-ab21-1f77246cce86"),
                            AlbumId = new Guid("a35a51d6-87a1-4989-a806-08494acf98e8"),
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Smells Like Teen Spirit",
                            TrackImageUrl = "https://i.discogs.com/MsIpIcpdbgg0r3CYB39OlwwuT81PuQ0psUcDvRLTdUU/rs:fit/g:sm/q:90/h:528/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MzI3/OC0xMzQwMTcwNjI1/LTMwNzguanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("e397b37c-bed7-4cf8-946a-54876e75e0ad"),
                            AlbumId = new Guid("a35a51d6-87a1-4989-a806-08494acf98e8"),
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "In Bloom",
                            TrackImageUrl = "https://i.discogs.com/6fsdEUC3-9WQy2tB4PmRvGcYrKPtggYbUSgD5QyZQQ4/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNDgz/ODctMTY4MDY3ODQ1/My05NTcwLmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("c12aac4a-c955-4bae-a531-1f9113ce0fec"),
                            AlbumId = new Guid("a35a51d6-87a1-4989-a806-08494acf98e8"),
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Come as You Are",
                            TrackImageUrl = "https://i.discogs.com/gIQVfX1uZI857sBz7NntFRdTCLO3eQT0o4qCiCIHnfE/rs:fit/g:sm/q:90/h:486/w:543/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc4MzIx/Ni0xNDE2ODkwNjQx/LTc3OTQuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("f2a6d8ef-6c6a-4150-9e34-1da2162b5f75"),
                            AlbumId = new Guid("a35a51d6-87a1-4989-a806-08494acf98e8"),
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Lithium",
                            TrackImageUrl = "https://i.discogs.com/hjHzpqaFqgJXi12l082Z4iIDAqkooFWzQOss9XzW6LU/rs:fit/g:sm/q:90/h:600/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyOTg2/OTQtMTU4NDk2NTg5/OS03MTUyLmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("44643fa2-43cb-418b-b40f-635326fd53bd"),
                            AlbumId = new Guid("12c850aa-c450-4af7-bb7b-7e98d5ce4956"),
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Serve the Servants",
                            TrackImageUrl = "https://i.discogs.com/mFtdd9bDwACrDsS9nQyxKcWlBY_WKlcIib_5iq0NspE/rs:fit/g:sm/q:90/h:522/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMjc5/MzMwLTE1MzIwMzE2/OTMtOTE3OC5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("291ce4f6-8db4-4098-bfcc-6083855859eb"),
                            AlbumId = new Guid("12c850aa-c450-4af7-bb7b-7e98d5ce4956"),
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Heart-Shaped Box",
                            TrackImageUrl = "https://i.discogs.com/jvt57zTP4f1brU4p_ABs9ylQ8K6B6a0El-CFqmHRyPU/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5MzA2/NS0xMTgyNjg0ODgz/LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("126eda42-d6ae-4eaa-b5bd-f679e0dfb232"),
                            AlbumId = new Guid("12c850aa-c450-4af7-bb7b-7e98d5ce4956"),
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Frances Farmer Will Have Her Revenge On Seattle",
                            TrackImageUrl = "https://i.discogs.com/FeGBBtykttDrTxPvdjPufzgY4HuxmQ_Yw-4F0ooQdCw/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MDE4/ODMyLTE1NjY3NjM4/MTctMzc3OS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("326cdf69-5b62-412b-9414-28fd6ae6f0ed"),
                            AlbumId = new Guid("12c850aa-c450-4af7-bb7b-7e98d5ce4956"),
                            ArtistId = new Guid("6ad74817-2c8c-4075-bf9d-00e9e700eb3e"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Pennyroyal Tea",
                            TrackImageUrl = "https://i.discogs.com/7W0cV6lsC_kWMo0sbFf1pd73ROkSNo6cpWEUHGrgdas/rs:fit/g:sm/q:90/h:462/w:596/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgyOTcz/My0xMTY1MTQ0MjEy/LmpwZWc.jpeg"
                        });
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.UserPlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MusicStoreApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MusicStoreApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlaylists");
                });

            modelBuilder.Entity("MusicStore.Domain.Identity.MusicStoreApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserCartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserCartId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TrackUserPlaylist", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TracksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlaylistsId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("TrackUserPlaylist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Album", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.BoughtItem", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.Order", "Order")
                        .WithMany("BoughtItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Order", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCart", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCartItem", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany("PurchasedTracks")
                        .HasForeignKey("MusicStoreApplicationUserId");

                    b.HasOne("MusicStore.Domain.Domain.ShoppingCart", "shoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shoppingCart");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Track", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.Domain.Domain.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.UserPlaylist", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany("MyPlaylists")
                        .HasForeignKey("MusicStoreApplicationUserId");

                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStore.Domain.Identity.MusicStoreApplicationUser", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.ShoppingCart", "UserCart")
                        .WithMany()
                        .HasForeignKey("UserCartId");

                    b.Navigation("UserCart");
                });

            modelBuilder.Entity("TrackUserPlaylist", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.UserPlaylist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.Domain.Domain.Track", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Order", b =>
                {
                    b.Navigation("BoughtItems");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MusicStore.Domain.Identity.MusicStoreApplicationUser", b =>
                {
                    b.Navigation("MyPlaylists");

                    b.Navigation("PurchasedTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
