// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStoreApplication.Repository;

#nullable disable

namespace MusicStore.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlbumImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a65ebb7-1ff0-4930-b2a0-36a6c7a48790"),
                            AlbumImageUrl = "https://i.discogs.com/1fwskTLM6cfxbdNmBDJ8expl6wab0tEgxvuloLIqKh8/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTkyODc4/MDktMTQ3OTc1MzIz/Ni05NjE3LmpwZWc.jpeg",
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Price = 20,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Side of the Moon"
                        },
                        new
                        {
                            Id = new Guid("2b62c76c-fa0a-4d44-b031-e3a00ff0b92d"),
                            AlbumImageUrl = "https://i.discogs.com/pZnTKUeiKsxSyvX_87YMgccx0bq5sjqThFH9iSNAtAY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYw/OTctOTI4MC5qcGVn.jpeg",
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Price = 22,
                            ReleaseDate = new DateTime(1975, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wish You Were Here"
                        },
                        new
                        {
                            Id = new Guid("6bedab31-c9aa-4c49-bfa2-cf2477ee75c5"),
                            AlbumImageUrl = "https://i.discogs.com/goWfjpqUBW8Y0xrqJG_GFz3fCTHPSWeKLZAX1alAAzk/rs:fit/g:sm/q:90/h:600/w:592/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MTg2/NDQxLTE1Njk0ODcx/NjEtNzMxNC5qcGVn.jpeg",
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Price = 25,
                            ReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Abbey Road"
                        },
                        new
                        {
                            Id = new Guid("b0921a71-b25d-4fb7-8d2f-9e0025a2170c"),
                            AlbumImageUrl = "https://i.discogs.com/HWA3uoT2xu7zj_kM-f18f02CCQNKk2W8YzUL-D_l2ZM/rs:fit/g:sm/q:90/h:581/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwODgx/MjYtMTI1Njk1MDk3/OS5qcGVn.jpeg",
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Price = 23,
                            ReleaseDate = new DateTime(1970, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Let It Be"
                        },
                        new
                        {
                            Id = new Guid("f120f6ef-be82-4617-97ea-0828ee628b56"),
                            AlbumImageUrl = "https://i.discogs.com/yFq3X0xZMxIVHIFgmbrsPvJHXLJCfVLWs60AL4XS4bs/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTM2NjMxMTg2/Ny0yNzg1LmpwZWc.jpeg",
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Price = 24,
                            ReleaseDate = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Led Zeppelin IV"
                        },
                        new
                        {
                            Id = new Guid("a41dfbec-fd86-4567-9e08-ddfea194a1fe"),
                            AlbumImageUrl = "https://i.discogs.com/BLWVi0t0llSqJvIybHrSvPql-RfORCmZU1klNfV0si8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xNTg4ODgwNzg4/LTIyMjYuanBlZw.jpeg",
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Price = 26,
                            ReleaseDate = new DateTime(1973, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Houses of the Holy"
                        },
                        new
                        {
                            Id = new Guid("f95a5849-a216-4e3e-bc09-3ba548823c95"),
                            AlbumImageUrl = "https://i.discogs.com/2GXnNYolz0ciUnj8-ycSwQ8Uuy0Qu7LCfiZivZ0p_bo/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQ1/LTIxMjcuanBlZw.jpeg",
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Price = 21,
                            ReleaseDate = new DateTime(1975, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Night at the Opera"
                        },
                        new
                        {
                            Id = new Guid("e2bd5edd-0b4b-4b3a-9d8e-d7022faabec7"),
                            AlbumImageUrl = "https://i.discogs.com/p2o5GGONaTq4jK398iU0X3KjuMfnK10_TEC_bdnKA6k/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzMjg5/ODItMTM1NzgxOTE3/NS05NTU3LmpwZWc.jpeg",
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Price = 19,
                            ReleaseDate = new DateTime(1984, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Works"
                        },
                        new
                        {
                            Id = new Guid("0673db40-90fa-4837-9dde-e4ef2d04d655"),
                            AlbumImageUrl = "https://i.discogs.com/XoAXkLe03Vk0Kt-oQqw7V9uW5nBzQdNvZd0zar5mOiQ/rs:fit/g:sm/q:90/h:592/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2NzA4/NC0xMjYzMDk1NTUz/LmpwZWc.jpeg",
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Price = 18,
                            ReleaseDate = new DateTime(1991, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nevermind"
                        },
                        new
                        {
                            Id = new Guid("7126cbd8-248f-4d4a-8aa8-5208f026342a"),
                            AlbumImageUrl = "https://i.discogs.com/ijIUNhH--0OKzKuKv-aLpgFkb7lr6OQVb5FcAF_aW0U/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NTk3/OS0xNDkxNzAwMzQ3/LTcyNjMuanBlZw.jpeg",
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Price = 20,
                            ReleaseDate = new DateTime(1993, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "In Utero"
                        });
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Bio = "A legendary rock band.",
                            Name = "Pink Floyd"
                        },
                        new
                        {
                            Id = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Bio = "One of the most influential rock bands.",
                            Name = "The Beatles"
                        },
                        new
                        {
                            Id = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Bio = "A rock band known for its heavy sound.",
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            Id = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Bio = "A rock band known for its eclectic musical style.",
                            Name = "Queen"
                        },
                        new
                        {
                            Id = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Bio = "A grunge band that shaped the 90s music scene.",
                            Name = "Nirvana"
                        });
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.BoughtItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("BoughtItems");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MusicStoreApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MusicStoreApplicationUserId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrackImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("403f1da6-8357-4c81-a182-ce0233d830d3"),
                            AlbumId = new Guid("7a65ebb7-1ff0-4930-b2a0-36a6c7a48790"),
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Duration = new TimeSpan(0, 0, 1, 0, 0),
                            Price = 129,
                            Title = "Speak to Me",
                            TrackImageUrl = "https://i.discogs.com/E9E7stvIt5YKUfK_CnrpIgxchviC7Q4WCeyQuuICAjo/rs:fit/g:sm/q:90/h:397/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTI0OTMwMDYw/MC5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("557ada45-4ede-4b16-9092-b4ad411479a7"),
                            AlbumId = new Guid("7a65ebb7-1ff0-4930-b2a0-36a6c7a48790"),
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Duration = new TimeSpan(0, 0, 2, 0, 0),
                            Price = 129,
                            Title = "Breathe in the air",
                            TrackImageUrl = "https://i.discogs.com/mfba8kz9-PIwZGE5g70Z5i6JpITmeRfaXLsWClcxj8g/rs:fit/g:sm/q:90/h:500/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4NzAw/MjYwLTE2OTgyMzg5/MDItNDY5NS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("530a3229-96c8-4042-8ced-3e8a246b7292"),
                            AlbumId = new Guid("7a65ebb7-1ff0-4930-b2a0-36a6c7a48790"),
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "On the Run",
                            TrackImageUrl = "https://i.discogs.com/t4BbENT4ugUFTY-pgCqTcEHhlfwlrJeJuyTOTzqxKfM/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTcyNzc2NDky/OS03ODUzLmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("341f5206-a73a-40ee-a1a5-e9d795bdb84b"),
                            AlbumId = new Guid("7a65ebb7-1ff0-4930-b2a0-36a6c7a48790"),
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Duration = new TimeSpan(0, 0, 6, 0, 0),
                            Price = 129,
                            Title = "Time",
                            TrackImageUrl = "https://i.discogs.com/rCpj_7gUWtxKDPQQpoVwbrud6zN2wwyQRVFR-ZaNtFI/rs:fit/g:sm/q:90/h:380/w:577/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4NzMw/MTMtMTI0OTMwMDU4/MS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("2ee65ebd-9ede-4933-a997-5f1261e91ca3"),
                            AlbumId = new Guid("2b62c76c-fa0a-4d44-b031-e3a00ff0b92d"),
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Duration = new TimeSpan(0, 0, 13, 0, 0),
                            Price = 129,
                            Title = "Shine On You Crazy Diamond (Part I-V)",
                            TrackImageUrl = "https://i.discogs.com/pZnTKUeiKsxSyvX_87YMgccx0bq5sjqThFH9iSNAtAY/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYw/OTctOTI4MC5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("69b090ff-171d-4424-a109-5ebcb33df2b2"),
                            AlbumId = new Guid("2b62c76c-fa0a-4d44-b031-e3a00ff0b92d"),
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Duration = new TimeSpan(0, 0, 7, 0, 0),
                            Price = 129,
                            Title = "Welcome to the Machine",
                            TrackImageUrl = "https://i.discogs.com/a36kcqXYhsvwN7S1cyq8_CGqqyWi78u3CLtxuE86-Go/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYw/OTYtMTc3Mi5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("154fc06e-4682-4756-8d74-66438ac8b6eb"),
                            AlbumId = new Guid("2b62c76c-fa0a-4d44-b031-e3a00ff0b92d"),
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Have a Cigar",
                            TrackImageUrl = "https://i.discogs.com/frk8i23GN3Epw5RaA-um7KwmBw0NTQiEHUYtirXaqdg/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYx/MDgtMTIxMi5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("f4a42742-d5c0-42a4-bcea-2f767de2cb44"),
                            AlbumId = new Guid("2b62c76c-fa0a-4d44-b031-e3a00ff0b92d"),
                            ArtistId = new Guid("b21ac1be-70bb-4950-9160-32cb64068b0e"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Wish You Were Here",
                            TrackImageUrl = "https://i.discogs.com/hJBh2v_V6Ow6_hyPu791g1d_Pqj6_aoKB6fm_JUKUPA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE2MjEx/ODEyLTE2MzczMzYx/MjgtNDE1My5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("2ed49b45-c954-4f64-a624-86a4d47d6026"),
                            AlbumId = new Guid("6bedab31-c9aa-4c49-bfa2-cf2477ee75c5"),
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Come Together",
                            TrackImageUrl = "https://i.discogs.com/M2yc5OJZPdVoDm2_UlRRXuDlDguamLLSdnbziNmZoQI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MDc0/MjQtMTYzMDYwMTA4/Ny0xMTk5LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("e52c7f3d-9043-4952-861d-02cd24133e8f"),
                            AlbumId = new Guid("6bedab31-c9aa-4c49-bfa2-cf2477ee75c5"),
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Something",
                            TrackImageUrl = "https://i.discogs.com/M2yc5OJZPdVoDm2_UlRRXuDlDguamLLSdnbziNmZoQI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MDc0/MjQtMTYzMDYwMTA4/Ny0xMTk5LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("c78010a7-d3b0-4dc8-896d-e6d914297de1"),
                            AlbumId = new Guid("6bedab31-c9aa-4c49-bfa2-cf2477ee75c5"),
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Octopus's Garden",
                            TrackImageUrl = "https://i.discogs.com/M2yc5OJZPdVoDm2_UlRRXuDlDguamLLSdnbziNmZoQI/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MDc0/MjQtMTYzMDYwMTA4/Ny0xMTk5LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("cc822355-0f0b-4cf6-a6c5-a505cd15f26c"),
                            AlbumId = new Guid("6bedab31-c9aa-4c49-bfa2-cf2477ee75c5"),
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Here Comes the Sun",
                            TrackImageUrl = "https://i.discogs.com/qsJyhu9LR8BERwbo5DRIYdNJzZFyuxQMr3RJcnOSEkw/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgxMzcz/NTUtMTQ1NTgzODU3/My0zNDk0LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("9449033d-83ea-4ddd-bfc6-8a2581dbf7f5"),
                            AlbumId = new Guid("b0921a71-b25d-4fb7-8d2f-9e0025a2170c"),
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Let It Be",
                            TrackImageUrl = "https://i.discogs.com/hAdrrjfnT2klIYc1V_oKX5HjpJ3xElwd7FDaDydTFGo/rs:fit/g:sm/q:90/h:600/w:566/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzU1/NC0xMzQ0NTE5Njg4/LTU0MzkuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("71d2beec-591b-4e06-952f-7b3ff54c5a46"),
                            AlbumId = new Guid("b0921a71-b25d-4fb7-8d2f-9e0025a2170c"),
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Across the Universe",
                            TrackImageUrl = "https://i.discogs.com/KFfU_VOBY43WsttSMHMp0uUvaQ8Sk63qAoCDeTeENpE/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzU1/NC0xMzQ1NjcxNjIy/LTM1ODYuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("1d6d52e1-0a22-4546-8f67-ef73762c1566"),
                            AlbumId = new Guid("b0921a71-b25d-4fb7-8d2f-9e0025a2170c"),
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "The Long and Winding Road",
                            TrackImageUrl = "https://i.discogs.com/3C94Ivdig0n1Jyb8d_0jKoIvj54r56hYW6kb6kiM8cY/rs:fit/g:sm/q:90/h:600/w:595/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzU1/NC0xMzI2NzA0NzMw/LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("31d5e2a7-af0e-4963-975f-f423a806d77c"),
                            AlbumId = new Guid("b0921a71-b25d-4fb7-8d2f-9e0025a2170c"),
                            ArtistId = new Guid("38dc46f6-3d37-4d60-9b7b-44354f613036"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Get Back",
                            TrackImageUrl = "https://i.discogs.com/yZ8hA52tgMGcdxfY182_OqxJIjUuzu1NvwVKxNM_Ztg/rs:fit/g:sm/q:90/h:599/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3NzU1/NC0xMzI2NzA0NzIw/LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("5c7b8133-b978-4760-b764-8a75ca7383b7"),
                            AlbumId = new Guid("f120f6ef-be82-4617-97ea-0828ee628b56"),
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Black Dog",
                            TrackImageUrl = "https://i.discogs.com/Ok43Qrm9pIMNTCCCR5oXwL9XU_0_WxXdRl6RKeXfxBg/rs:fit/g:sm/q:90/h:600/w:595/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTU5Mjc0NzQ3/My00NDI0LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("ffdc047c-267e-4536-9f94-94b7f7fd0ba4"),
                            AlbumId = new Guid("f120f6ef-be82-4617-97ea-0828ee628b56"),
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Rock and Roll",
                            TrackImageUrl = "https://i.discogs.com/aFc_fainrAcSiX2MbERPPWWlvjeYKc0D4yf53WD4rzM/rs:fit/g:sm/q:90/h:592/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTU5Mjc0NzQ3/NC00ODYwLmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("42a546ce-087c-4412-b346-89b2404a5b2e"),
                            AlbumId = new Guid("f120f6ef-be82-4617-97ea-0828ee628b56"),
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Duration = new TimeSpan(0, 0, 8, 0, 0),
                            Price = 129,
                            Title = "Stairway to Heaven",
                            TrackImageUrl = "https://i.discogs.com/AO-PmjrMZa3JNJ8NBErUUcDOJ2Yna2jCNLbwmZ0n9aE/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc1Nzg1/NC0xNTE1ODU0Mjcx/LTM3NDUuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("e91e9662-11bc-4271-a2f2-66d7e44c4d36"),
                            AlbumId = new Guid("f120f6ef-be82-4617-97ea-0828ee628b56"),
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Going to California",
                            TrackImageUrl = "https://i.discogs.com/kOYbkKoJqpZfHNMg38TaBrOQmJWYO8UoRWV_BOgR6MA/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEwMTU0/NjUtMTM2NjMxMTg4/My02MDE1LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("600bb873-295b-4df3-b85a-2b578bffa911"),
                            AlbumId = new Guid("a41dfbec-fd86-4567-9e08-ddfea194a1fe"),
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "The Song Remains the Same",
                            TrackImageUrl = "https://i.discogs.com/PGoolvGRHExppmuvEDxPETmRJAFIlpoSAZ41ws86GLw/rs:fit/g:sm/q:90/h:577/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xMzkxNTIyMzA2/LTU4MzMuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("33fef7c1-f037-4d1c-a2fc-c879e75821f7"),
                            AlbumId = new Guid("a41dfbec-fd86-4567-9e08-ddfea194a1fe"),
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Duration = new TimeSpan(0, 0, 7, 0, 0),
                            Price = 129,
                            Title = "The Rain Song",
                            TrackImageUrl = "https://i.discogs.com/8wnDvfzEjV9Wc1BBxbaIIUeBhIxQ7WeFsKjdwt9hoWc/rs:fit/g:sm/q:90/h:574/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xMzkxNTIyMjY2/LTY4MzkuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("ed29b179-968a-409d-baa0-34b6d72e21ad"),
                            AlbumId = new Guid("a41dfbec-fd86-4567-9e08-ddfea194a1fe"),
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Over the Hills and Far Away",
                            TrackImageUrl = "https://i.discogs.com/QVRkVVBO1gFfafoFfNzNps67VKs1DsGRcHQ474zEDf0/rs:fit/g:sm/q:90/h:224/w:452/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xMTcxOTI0MzQz/LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("f9b212d4-1ffa-49b6-bc87-d0f15e59d1ac"),
                            AlbumId = new Guid("a41dfbec-fd86-4567-9e08-ddfea194a1fe"),
                            ArtistId = new Guid("bc7f8cff-deb7-4d49-a9e6-6bb2d65b353f"),
                            Duration = new TimeSpan(0, 0, 7, 0, 0),
                            Price = 129,
                            Title = "No Quarter",
                            TrackImageUrl = "https://i.discogs.com/BLWVi0t0llSqJvIybHrSvPql-RfORCmZU1klNfV0si8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ1NTA3/Ny0xNTg4ODgwNzg4/LTIyMjYuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("9041d29c-b65e-42bd-b527-8aa4127f4151"),
                            AlbumId = new Guid("f95a5849-a216-4e3e-bc09-3ba548823c95"),
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Death on Two Legs",
                            TrackImageUrl = "https://i.discogs.com/exLiE9TUHd1Osv4-SBjJsO8zScHQQ2s5XTA7QzvHmjk/rs:fit/g:sm/q:90/h:591/w:595/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQy/LTU2OTMuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("ddb625ea-003e-410a-a965-34e753cb1ae5"),
                            AlbumId = new Guid("f95a5849-a216-4e3e-bc09-3ba548823c95"),
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "You're My Best Friend",
                            TrackImageUrl = "https://i.discogs.com/2GXnNYolz0ciUnj8-ycSwQ8Uuy0Qu7LCfiZivZ0p_bo/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQ1/LTIxMjcuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("3e8c44ed-bcad-431b-85ad-a36140974f35"),
                            AlbumId = new Guid("f95a5849-a216-4e3e-bc09-3ba548823c95"),
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Love of My Life",
                            TrackImageUrl = "https://i.discogs.com/2GXnNYolz0ciUnj8-ycSwQ8Uuy0Qu7LCfiZivZ0p_bo/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxMjc4/MC0xNTQxMzY3MTQ1/LTIxMjcuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("e453862a-57b8-4b19-a885-6c0348a175d3"),
                            AlbumId = new Guid("f95a5849-a216-4e3e-bc09-3ba548823c95"),
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Duration = new TimeSpan(0, 0, 6, 0, 0),
                            Price = 129,
                            Title = "Bohemian Rhapsody",
                            TrackImageUrl = "https://i.discogs.com/_RN78C49qgCxMX3CnRdxDggOCSI5P7uYaUGJ_Pl_CGM/rs:fit/g:sm/q:90/h:567/w:574/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2OTg5/MC0xMzkzMjg2NDQz/LTU3NTUuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("9708bee3-4e55-473d-a74a-4134117a872f"),
                            AlbumId = new Guid("e2bd5edd-0b4b-4b3a-9d8e-d7022faabec7"),
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Radio Ga Ga",
                            TrackImageUrl = "https://i.discogs.com/b20JvPlll2B74GR7tMh3oSukHbeTjq3cyTBpdKk25fA/rs:fit/g:sm/q:90/h:600/w:598/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1MTU5/MTEtMTU5OTIzODcx/MS05NjI1LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("1537e6c8-b4f9-46f8-819b-1844fddf14d6"),
                            AlbumId = new Guid("e2bd5edd-0b4b-4b3a-9d8e-d7022faabec7"),
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Tear It Up",
                            TrackImageUrl = "https://i.discogs.com/TNq6BKsREuTvVL0QtgziQ0ACcLNhKq9AjP-NYI7yo14/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTQ3NTU5/Ni0xNDU0NzA3NDYw/LTIxNzkuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("231c7dd6-06ac-4651-b9e9-1b220e635cbb"),
                            AlbumId = new Guid("e2bd5edd-0b4b-4b3a-9d8e-d7022faabec7"),
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "It's a Hard Life",
                            TrackImageUrl = "https://i.discogs.com/gdK1Z8e8y1qZybHe6WF_NXUstJzEhHSId63nx0GS_Yo/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1OTU3/NTktMTIzMTA1Njkw/MS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("b49acbdb-456c-4057-ba59-32fb52aab890"),
                            AlbumId = new Guid("e2bd5edd-0b4b-4b3a-9d8e-d7022faabec7"),
                            ArtistId = new Guid("d176df78-ab3e-4d82-baed-0ac92b4f0a4c"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "I Want to Break Free",
                            TrackImageUrl = "https://i.discogs.com/GZW57VCYRIgmdlkLRQwj_ZejpTs1lW3TiH-m5zJzvKg/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1NDU5/MDAtMTIyNzQzNTEx/NS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("37c97584-e59c-48df-b2df-36022128f0ed"),
                            AlbumId = new Guid("0673db40-90fa-4837-9dde-e4ef2d04d655"),
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Smells Like Teen Spirit",
                            TrackImageUrl = "https://i.discogs.com/MsIpIcpdbgg0r3CYB39OlwwuT81PuQ0psUcDvRLTdUU/rs:fit/g:sm/q:90/h:528/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MzI3/OC0xMzQwMTcwNjI1/LTMwNzguanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("906d8cbc-e4b3-4219-86b8-3cfdef07ba87"),
                            AlbumId = new Guid("0673db40-90fa-4837-9dde-e4ef2d04d655"),
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "In Bloom",
                            TrackImageUrl = "https://i.discogs.com/6fsdEUC3-9WQy2tB4PmRvGcYrKPtggYbUSgD5QyZQQ4/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEzNDgz/ODctMTY4MDY3ODQ1/My05NTcwLmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("18b65708-07dd-496e-8ae2-c3cc05c00a27"),
                            AlbumId = new Guid("0673db40-90fa-4837-9dde-e4ef2d04d655"),
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Come as You Are",
                            TrackImageUrl = "https://i.discogs.com/gIQVfX1uZI857sBz7NntFRdTCLO3eQT0o4qCiCIHnfE/rs:fit/g:sm/q:90/h:486/w:543/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc4MzIx/Ni0xNDE2ODkwNjQx/LTc3OTQuanBlZw.jpeg"
                        },
                        new
                        {
                            Id = new Guid("455c6e03-4290-450d-bf09-02621fa8c5cf"),
                            AlbumId = new Guid("0673db40-90fa-4837-9dde-e4ef2d04d655"),
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Lithium",
                            TrackImageUrl = "https://i.discogs.com/hjHzpqaFqgJXi12l082Z4iIDAqkooFWzQOss9XzW6LU/rs:fit/g:sm/q:90/h:600/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyOTg2/OTQtMTU4NDk2NTg5/OS03MTUyLmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("88289a3b-1afb-4aed-a84e-97a969959514"),
                            AlbumId = new Guid("7126cbd8-248f-4d4a-8aa8-5208f026342a"),
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Serve the Servants",
                            TrackImageUrl = "https://i.discogs.com/mFtdd9bDwACrDsS9nQyxKcWlBY_WKlcIib_5iq0NspE/rs:fit/g:sm/q:90/h:522/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTEyMjc5/MzMwLTE1MzIwMzE2/OTMtOTE3OC5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("fa5dafc0-65d2-42d1-8834-b9b6412d2f1f"),
                            AlbumId = new Guid("7126cbd8-248f-4d4a-8aa8-5208f026342a"),
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Duration = new TimeSpan(0, 0, 5, 0, 0),
                            Price = 129,
                            Title = "Heart-Shaped Box",
                            TrackImageUrl = "https://i.discogs.com/jvt57zTP4f1brU4p_ABs9ylQ8K6B6a0El-CFqmHRyPU/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM5MzA2/NS0xMTgyNjg0ODgz/LmpwZWc.jpeg"
                        },
                        new
                        {
                            Id = new Guid("68351b85-4723-46ed-adf7-c7db6175e53b"),
                            AlbumId = new Guid("7126cbd8-248f-4d4a-8aa8-5208f026342a"),
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Duration = new TimeSpan(0, 0, 3, 0, 0),
                            Price = 129,
                            Title = "Frances Farmer Will Have Her Revenge On Seattle",
                            TrackImageUrl = "https://i.discogs.com/FeGBBtykttDrTxPvdjPufzgY4HuxmQ_Yw-4F0ooQdCw/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MDE4/ODMyLTE1NjY3NjM4/MTctMzc3OS5qcGVn.jpeg"
                        },
                        new
                        {
                            Id = new Guid("86863715-f532-4a4e-9fdc-4e62c7067851"),
                            AlbumId = new Guid("7126cbd8-248f-4d4a-8aa8-5208f026342a"),
                            ArtistId = new Guid("437b71ca-0899-4a88-9555-0260005d7813"),
                            Duration = new TimeSpan(0, 0, 4, 0, 0),
                            Price = 129,
                            Title = "Pennyroyal Tea",
                            TrackImageUrl = "https://i.discogs.com/7W0cV6lsC_kWMo0sbFf1pd73ROkSNo6cpWEUHGrgdas/rs:fit/g:sm/q:90/h:462/w:596/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTgyOTcz/My0xMTY1MTQ0MjEy/LmpwZWc.jpeg"
                        });
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.UserPlaylist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MusicStoreApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MusicStoreApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlaylists");
                });

            modelBuilder.Entity("MusicStore.Domain.Identity.MusicStoreApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserCartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserCartId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TrackUserPlaylist", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TracksId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlaylistsId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("TrackUserPlaylist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Album", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.BoughtItem", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.Order", "Order")
                        .WithMany("BoughtItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Order", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCart", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCartItem", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany("PurchasedTracks")
                        .HasForeignKey("MusicStoreApplicationUserId");

                    b.HasOne("MusicStore.Domain.Domain.ShoppingCart", "shoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("shoppingCart");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Track", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.Domain.Domain.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.UserPlaylist", b =>
                {
                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", null)
                        .WithMany("MyPlaylists")
                        .HasForeignKey("MusicStoreApplicationUserId");

                    b.HasOne("MusicStore.Domain.Identity.MusicStoreApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicStore.Domain.Identity.MusicStoreApplicationUser", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.ShoppingCart", "UserCart")
                        .WithMany()
                        .HasForeignKey("UserCartId");

                    b.Navigation("UserCart");
                });

            modelBuilder.Entity("TrackUserPlaylist", b =>
                {
                    b.HasOne("MusicStore.Domain.Domain.UserPlaylist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStore.Domain.Domain.Track", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Album", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.Order", b =>
                {
                    b.Navigation("BoughtItems");
                });

            modelBuilder.Entity("MusicStore.Domain.Domain.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MusicStore.Domain.Identity.MusicStoreApplicationUser", b =>
                {
                    b.Navigation("MyPlaylists");

                    b.Navigation("PurchasedTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
